courses/urls.py
from django.urls import path
from .views import CourseList, CourseDetail, LessonDetail
app_name = 'courses'
urlpatterns = [
    path('', CourseList.as_view(), name='list'),
    path('<slug>/', CourseDetail.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>/', LessonDetail.as_view(), name='lesson-detail')
]

kaytutors/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('courses/', include('courses.urls', namespace='courses')),
    path('memberships/', include('memberships.urls', namespace='memberships')),
    path('users/', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memberships/urls.py
from django.urls import path
from .views import MembershipList, PaymentView, updateTransactions, profile, cancelSubscription
app_name = 'memberships'
urlpatterns = [
    path('', MembershipList.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactions, name='update-transactions'),
    path('profile/', profile, name='profile'),
    path('cancel/', cancelSubscription, name='cancel')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import Register
app_name = 'users'
urlpatterns = [
    path('register/', Register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

courses/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership

# Create your models here.


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    position = models.IntegerField(default=1)
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')



class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    content = models.TextField(blank=True, null=True)
    position = models.IntegerField()
    video = models.FileField(blank=True, null=True)
    thumbnail = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={
            'course_slug': self.course.slug,
            'lesson_slug': self.slug
        })

    @property
    def video_url(self):
        if self.video and hasattr(self.video, 'url'):
            return self.video.url

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Course, Lesson
from memberships.models import UserMembership
# Create your views here.


class CourseList(ListView):
    model = Course
    template_name = 'courses/course_list.html'
    def get_queryset(self):
        course = Course.objects.all().order_by('position')
        return course


class CourseDetail(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/course_detail.html'


class LessonDetail(LoginRequiredMixin, View):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        user_membership = get_object_or_404(UserMembership, user=request.user)
        user_membership_type = user_membership.membership.membership_type
        course_allowed_mem_types = course.allowed_membership.all()
        context = {'object': None}
        if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
            context = {
                'object': lesson
            }
        return render(request, 'courses/lesson_detail.html', context)

courses/templates/courses/base.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
{% include 'courses/messages.html' %}
		<ol class='breadcrumb'>
            <li><a href="{% url 'home' %}">Home</a></li>

	        {% if not request.user.is_authenticated %}
	        <li class='pull-right'><a href="{% url 'users:register' %}">Register</a></li>
	        <li class='pull-right'><a href="{% url 'users:login' %}">Login</a></li>
		{% else %}
		<li class='pull-right'><a href="{% url 'users:logout' %}">Logout</a></li>
		<li class='pull-right'><a href="{% url 'memberships:select' %}">Memberships</a></li>
         <li><a href="{% url 'courses:list' %}">Courses</a></li>
		<li><a href="{% url 'memberships:profile' %}">Profile</a></li>
	        {% endif %}
	    </ol>
	</div>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
</script>
</body>
</html>

courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}
{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-sm-8 col-md-8'>
            <h1>Course</h1>
    <p>{{ object.title }}</p>
    <p>{{ object.description }}</p>
    <ol>
    {% for lesson in object.lessons %}
        <li><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></li>
    {% endfor %}
    </ol>
    </div>
    </div>
    </div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}
{% block content %}
<div class='container'>
    <div class='row'>
    <h1>Courses Available</h1>
    <div class='col-sm-8 col-md-8'>
    {% for object in object_list %}
        <ul>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    {% endfor %}
    </div>
    </div>
    </div>
{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}
<div class='container'>
    <h1>Lesson</h1>
    <div class='row'>
        <div class='col-sm-8 col-md-8'>
    {% if object is not None %}
        {% if object.video_url %}
        <h3>{{ object.title }}</h3>
        <p>{{ object.content }}</p>
        <video
        poster="{{ object.thumbnail.url }}"
        width="450"
        height="350" controls>
        <source src="{{ object.video_url }}" type="video/mp4">
        Sorry, your browser doesn't support embedded window.
        </video>
            {% endif %}
        {% else %}
{#        <h3>Upgrade membership</h3>#}
        <p>To view this course, you will need to upgrade or cancel your membership</p>
        <br>
        <a href="{% url 'memberships:select' %}"><button class='btn btn-warning'>Check out Memberships</button></a>
        <hr>
    {% endif %}
    </div>
    </div>
    </div>
{% endblock %}

courses/templates/courses/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: darkgreen;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>
    <ul class="messages">
    {% for message in messages %}
    <li>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>
    </div>
{% endif %}